import matplotlib.pyplot as plt

def plotEverything(xin,xpin,yin,ypin,alpha_x,beta_x,epsilon_x,alpha_y,beta_y,epsilon_y,xo,xpo,yo,ypo,envx,envy):
    plt.figure(0)
    ax1 = plt.subplot2grid((4,3), (0,0))
    plt.plot(xin,xpin,'ro')
    plt.title('Initial value in x')
    plt.xlabel('x')
    plt.ylabel('xp')
    ax2 = plt.subplot2grid((4,3), (0,1))
    plt.plot(yin,ypin,'bo')
    plt.title('Initial value in y')
    plt.xlabel('y')
    plt.ylabel('yp')
    ax3 = plt.subplot2grid((4,3), (0,2))
    plt.plot(xin,yin,'go')
    plt.title('Initial values x and y')
    plt.xlabel('x')
    plt.ylabel('y')
    ax4 = plt.subplot2grid((4,3), (1, 0), colspan=3)
    plt.plot(envx[:,0],envx[:,1],'ro')
    plt.title('Envelope in x by z')
    plt.xlabel('z')
    plt.ylabel('Envelope in x')
    ax5 = plt.subplot2grid((4,3), (2, 0), colspan=3)
    plt.plot(envy[:,0],envy[:,1],'bo')
    plt.title('Envelope in y by z')
    plt.xlabel('z')
    plt.ylabel('Envelope in y')
    ax6 = plt.subplot2grid((4,3), (3, 0))
    plt.plot(xo,xpo,'ro')
    plt.title('Values after FODO in x')
    plt.xlabel('x')
    plt.ylabel('xp')
    ax7 = plt.subplot2grid((4,3), (3, 1))
    plt.plot(yo,ypo,'bo')
    plt.title('Values after FODO in y')
    plt.xlabel('y')
    plt.ylabel('yp')
    ax8 = plt.subplot2grid((4,3), (3, 2))
    plt.plot(xo,yo,'go')
    plt.title('Values after FODO in y and x')
    plt.xlabel('x')
    plt.ylabel('y')

    plt.suptitle("Plots")
    plt.show()

def plotEnvelope(envx,envy):
    plt.figure(0)
    ax4 = plt.subplot2grid((2,3), (0, 0), colspan=3)
    plt.plot(envx[:,0],envx[:,1],'ro')
    plt.title('Envelope in x by z')
    plt.xlabel('z')
    plt.ylabel('Envelope in x')
    ax5 = plt.subplot2grid((2,3), (1, 0), colspan=3)
    plt.plot(envy[:,0],envy[:,1],'bo')
    plt.title('Envelope in y by z')
    plt.xlabel('z')
    plt.ylabel('Envelope in y')

    plt.show()